config/routes.rb
DrawADistrict::Application.routes.draw do
  devise_for :users
  root to: "welcome#home"
  resources :addresses do
    collection { post :import }
  end
  resources :custom_map
  resources :documents
  get "users/list" => "users#list", as: :user_list
end

app/models/document.rb
class Document
  include Mongoid::Document
  field :name, type: String
  embeds_many :addresses, class_name: "Address", inverse_of: :addresser

  def to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["CUST_ID", "COMPANY_NM" "ADDRESS", "COORDINATES", "DISTRICT"]
      addresses.each do |address|
        csv << [address.cust_id, address.name, address.text, address.coordinates, address.district]
      end
    end
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @documents = Document.all
    @maps = CustomMap.all
  end

  def show
    @document = Document.find(params[:id])
    @error_queue = []
    @addresses = []
    @document.addresses.each do |address|
      if address.district == "erro"
        @error_queue.push(address)
      else
        @addresses.push(address)
      end
    end
    @hash = Gmaps4rails.build_markers(@addresses) do |address, marker|
      if address.district == "erro"
        @error_queue.push(address)
      else
        marker.lat address.to_coordinates[0]
        marker.lng address.to_coordinates[1]
        marker.infowindow render_to_string(:partial => "/addresses/tooltips", :locals => { :object => address})
      end
    end
    gon.push({
      :hash => @hash
    })
    respond_to do |format|
      format.html
      format.csv { render text: @document.to_csv }
      format.xls { send_data @document.to_csv(col_sep: "\t") }
    end
  end

  def destroy
    @document = Document.find(params[:id])
    if current_user.admin == true
      @document.destroy!
      redirect_to :root, notice: 'Document Deleted'
    else
      flash[:notice] = "You do not have sufficient permissions to do that."
    end
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/index.html.erb
<br><br>
<div class="container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Uploaded Documents</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Download</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @documents.each do |document| %>
          <tr><td><%= link_to document.name, document_path(document.id) %></td> 
              <td><%= link_to "CSV", document_path(document.id, format: "csv") %></td>
            <% if current_user.admin == true %>
              <td><%= button_to "Delete", document, method: :delete %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Upload New Document</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <%= form_tag import_addresses_path, multipart: true do %>
            <th><%= file_field_tag :file %></th>
            <th><%= submit_tag "Import" %></th>
          <% end %>
        </tr>
      </thead>
    </table>
  </div>

  <% if current_user.admin == true %>
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">Custom Maps <strong>(Feature in Beta: Admin Users Only)</strong></div>
      <!-- Table -->
      <table class="table">
        <tbody>
          <tr>
            <% @maps.each do |map| %>
              <tr>
                <td><%= link_to map.name, custom_map_path(map.id) %></td>
                <td><%= button_to "Delete", map, method: :delete %></td>
              </tr>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="panel-footer"><%= button_to "New Custom Map", new_custom_map_path %></div>
    </div>
  <% end %>

  </div>