config/routes.rb
DrawADistrict::Application.routes.draw do
  devise_for :users
  root to: "welcome#home"
  resources :addresses do
    collection { post :import }
  end
  resources :custom_map
  resources :documents
  get "users/list" => "users#list", as: :user_list
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!

  def import
    @address = Address.import(params[:file])
    if @address == false
      redirect_to documents_path, notice: "Input field cannot be blank. Please select a spreadsheet and try again."
    else
      redirect_to documents_path, notice: "CSV successfully imported."
    end
  end

  def index
    @addresses = Address.all
    @hash = Gmaps4rails.build_markers(@addresses) do |address, marker|
      marker.lat address.to_coordinates[0]
      marker.lng address.to_coordinates[1]
    end
    gon.push({
      :hash => @hash
    })
    respond_to do |format|
      format.html
      format.csv { render text: @addresses.to_csv }
      format.xls { send_data @addresses.to_csv(col_sep: "\t") }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_tooltips.html.erb
<%=   object.name %><br>
District: <%= object.district %><br>
<%=   object.text %>

app/views/addresses/index.html.erb
<br><br>
<div class="col-lg-7">
  <p>
    Download:
    <%= link_to "CSV", addresses_path(format: "csv") %> | <%= link_to "XLS", addresses_path(format: "xls") %>
  </p>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Your Uploaded Addresses</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>Address</th>
          <th>Coordinates</th>
          <th>District</th>
        </tr>
      </thead>
      <tbody>
        <% @addresses.each do |address| %>
          <tr><td><%= address.text %></td> <td><%= address.to_coordinates %></td> <td><%= address.district %></td></tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Upload Additional Addresses</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <%= form_tag import_addresses_path, multipart: true do %>
            <th><%= file_field_tag :file %></th>
            <th><%= submit_tag "Import" %></th>
          <% end %>
        </tr>
      </thead>
    </table>
  </div>
</div>

<div class="col-lg-5">
  <div class="container">
    <br>
    <div style='width: 400px;'>
      <div id="map" style='width: 400px; height: 400px;'></div>
    </div>
<!--     Eventual Legend -->
<!--     <div class="col-xs-2">
      <ul>
        <li>District 1</li>
        <li>District 2</li>
        <li>District 3</li>
        <li>District 4</li>
      </ul>
    </div>
    <div class="col-xs-2">
      <ul>
        <li>District 5</li>
        <li>District 6</li>
        <li>District 7</li>
      </ul>
    </div> -->

    <%= javascript_include_tag "polymap.js" %>
  <div class="container">
</div>