config/routes.rb
DrawADistrict::Application.routes.draw do
  devise_for :users
  root to: "welcome#home"
  resources :addresses do
    collection { post :import }
  end
  resources :custom_map
  resources :documents
  get "users/list" => "users#list", as: :user_list
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map My Districts</title>
  <%= include_gon %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Map My Districts</a>
    </div>
    <div class="collapse navbar-collapse">
      <div id="user_nav">
        <% if user_signed_in? %>
        <p class="navbar-text navbar-right"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
        <p class="navbar-text navbar-right"><%= link_to 'Edit profile', edit_user_registration_path  %></p>
        <p class="navbar-text navbar-right"><%= link_to 'All Users', user_list_path %></p>
        <p class="navbar-text navbar-right">Logged in as 
          <strong><%= current_user.email %>
            <%if current_user.admin == true%>
              :  ADMIN
            <%end%>
          </strong>
        </p>
        <% else %>
          <p class="navbar-text navbar-right"><%= link_to "Login", new_user_session_path %></p>
          <p class="navbar-text navbar-right"><%= link_to "Sign up", new_user_registration_path %></p>
        <% end %>
      </div>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</div>

<br><br>

<% if flash.notice %>
  <div class="alert alert-info"><%= flash.notice %></div>
<% end %>


<%= yield %>

</body>
</html>

app/views/layouts/headless.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map My Districts</title>
  <%= include_gon %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>
  <style type="text/css">
    body { background-color: #B8E6B8 !important }
  </style>

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Seattle Chamber of Commerce District Mapper</a>
    </div>
    <div class="nav navbar-collapse pull-right">
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</div>

<br><br>

<% if flash.notice %>
  <div class="alert alert-info"><%= flash.notice %></div>
<% end %>


<%= yield %>

</body>
</html>